In [3]:
import numpy as np

arr = np.array(range(1, 11))
print (arr)
print (arr * 3)
print (arr + 5)
print (arr ** 2)

arr_2d = np.ones((3,3))
print (arr_2d)

[ 1  2  3  4  5  6  7  8  9 10]
[ 3  6  9 12 15 18 21 24 27 30]
[ 6  7  8  9 10 11 12 13 14 15]
[  1   4   9  16  25  36  49  64  81 100]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [5]:
import pandas as pd

df = pd.read_csv("data_latihan.csv")
df

nama  umur  nilai
0   Budi    23     80
1  Siska    21     90
2   Andi    25     75
3   Dewi    22     88

In [6]:
df.head()

nama  umur  nilai
0   Budi    23     80
1  Siska    21     90
2   Andi    25     75
3   Dewi    22     88

In [7]:
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   nama    4 non-null      str  
 1   umur    4 non-null      int64
 2   nilai   4 non-null      int64
dtypes: int64(2), str(1)
memory usage: 228.0 bytes


umur      nilai
count   4.000000   4.000000
mean   22.750000  83.250000
std     1.707825   6.994045
min    21.000000  75.000000
25%    21.750000  78.750000
50%    22.500000  84.000000
75%    23.500000  88.500000
max    25.000000  90.000000

In [8]:
df[df['nilai'] > 80]

nama  umur  nilai
1  Siska    21     90
3   Dewi    22     88

In [9]:
df['nilai_total'] = df['nilai'] * 1.1

In [11]:
df.to_csv("output_modul2.csv", index=False)